Install Libraries

In [2]:
!pip -q install langchain langchain-groq python-dotenv rich scikit-learn pandas

In [3]:
!pip -q install pyautogen groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.3/119.3 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.9/101.9 kB 4.1 MB/s eta 0:00:00

In [4]:
from google.colab import userdata

GROQ_API_KEY = userdata.get("GROQ_API_KEY")

In [5]:
from langchain_groq import ChatGroq

In [6]:
from google.colab import userdata
from langchain_groq import ChatGroq

GROQ_API_KEY = userdata.get("GROQ_API_KEY")

llm = ChatGroq(
    groq_api_key=GROQ_API_KEY,
    model_name="llama-3.3-70b-versatile",
    temperature=0
)

Import Section

In [7]:
import io
import sys
import pandas as pd
import numpy as np

from sklearn.ensemble import IsolationForest

from google.colab import userdata
from langchain_groq import ChatGroq

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.syntax import Syntax
from rich import box

# -----------------------------
# Load Groq API Key
# -----------------------------
GROQ_API_KEY = userdata.get("GROQ_API_KEY")

# -----------------------------
# Rich Console
# -----------------------------
console = Console()

# -----------------------------
# Load Dataset
# -----------------------------
df = pd.read_csv("dataset.csv")

console.print("\n[bold green]Dataset loaded successfully[/bold green]\n")

table = Table(title="Dataset Preview", box=box.DOUBLE_EDGE)

for col in df.columns:
    table.add_column(col)

for _, row in df.iterrows():
    table.add_row(*[str(i) for i in row])

console.print(table)

# -----------------------------
# Groq LLM
# -----------------------------
llm = ChatGroq(
    groq_api_key=GROQ_API_KEY,
    model_name="llama-3.3-70b-versatile",
    temperature=0
)

# -----------------------------
# Agent 1 - Guiding Agent
# -----------------------------
tasks = [
    "Display the entire dataset",
    "Print number of rows, number of columns and column names",
    "Identify and print quantitative and qualitative columns",
    "Detect missing values, print number of missing values and handle them",
    "Detect outliers, print high and low outliers and handle them using IQR",
    "Find duplicates and print number of duplicate rows",
]

# -----------------------------
# Agent 2 - Coding Agent
# -----------------------------
def coder_agent(task):

    prompt = f"""
You are an expert Python data preprocessing engineer.

Rules:
1. Dataframe name is df
2. Use pandas and numpy
3. Do NOT reload dataset
4. Numeric columns = df.select_dtypes(include=np.number)
5. Categorical columns = df.select_dtypes(include="object")
6. Return ONLY executable Python code.
7. Do not use markdown.
8. Do not use explanations.

Task:
{task}
"""

    response = llm.invoke(prompt)

    code = response.content.strip()
    code = code.replace("```python", "").replace("```", "").strip()

    console.print("\n[bold yellow]Generated Code[/bold yellow]\n")
    console.print(Syntax(code, "python", theme="monokai"))

    return code

# -----------------------------
# Agent 3 - Executor Agent
# -----------------------------
def executor_agent(code):

    global df

    try:

        local_vars = {
            "df": df,
            "np": np,
            "pd": pd,
            "IsolationForest": IsolationForest
        }

        buffer = io.StringIO()
        old_stdout = sys.stdout
        sys.stdout = buffer

        exec(code, globals(), local_vars)

        sys.stdout = old_stdout

        df = local_vars.get("df", df)

        output = buffer.getvalue()

        console.print(
            Panel(
                output if output else "Execution Completed",
                title="Execution Output",
                style="bold cyan"
            )
        )

    except Exception as e:

        sys.stdout = sys.__stdout__

        console.print(
            Panel(
                str(e),
                title="Execution Error",
                style="bold red"
            )
        )

# -----------------------------
# Agent 4 - Checker Agent
# -----------------------------
def checker_agent(iteration):

    if iteration < len(tasks):
        console.print(
            "\n[bold cyan]Checker Agent → Pending Preprocessing[/bold cyan]"
        )
    else:
        console.print(
            "\n[bold green]Checker Agent → Preprocessed Completely[/bold green]"
        )

# -----------------------------
# Multi-Agent Workflow
# -----------------------------
for i, task in enumerate(tasks, start=1):

    console.print(
        f"\n[bold magenta]========== Iteration {i} ==========[/bold magenta]"
    )

    console.print(f"[bold blue]Guiding Agent → {task}[/bold blue]")

    code = coder_agent(task)

    executor_agent(code)

    checker_agent(i)

# -----------------------------
# Final Dataset
# -----------------------------
console.print("\n[bold green]Final Cleaned Dataset[/bold green]\n")

final_table = Table(title="Processed Dataset", box=box.DOUBLE_EDGE)

for col in df.columns:
    final_table.add_column(col)

for _, row in df.iterrows():
    final_table.add_row(*[str(i) for i in row])

console.print(final_table)

# -----------------------------
# Save Dataset
# -----------------------------
output_file = "Final_Dataset.csv"

df.to_csv(output_file, index=False)

console.print(
    f"\n[bold green]Dataset saved as {output_file}[/bold green]"
)

Dataset loaded successfully

                        Dataset Preview
╔════════════╤═════════╤══════════╤═══════════════╤═══════════╗
║ date       │ sku     │ location │ quantity_sold │ inventory ║
╟────────────┼─────────┼──────────┼───────────────┼───────────╢
║ 2024-01-01 │ SKU_101 │ Chennai  │ 52.0          │ 120       ║
║ 2024-01-02 │ SKU_101 │ Chennai  │ 49.0          │ 115       ║
║ 2024-01-03 │ SKU_101 │ Chennai  │ nan           │ 110       ║
║ 2024-01-04 │ SKU_101 │ Chennai  │ 55.0          │ 105       ║
║ 2024-01-05 │ SKU_101 │ Chennai  │ 60.0          │ 100       ║
║ 2024-01-06 │ SKU_101 │ Chennai  │ -5.0          │ 95        ║
║ 2024-01-07 │ SKU_101 │ Chennai  │ 58.0          │ 90        ║
║ 2024-01-08 │ SKU_101 │ Chennai  │ 62.0          │ 85        ║
║ 2024-01-09 │ SKU_101 │ Chennai  │ 59.0          │ 80        ║
║ 2024-01-10 │ SKU_101 │ Chennai  │ 57.0          │ 75        ║
║ 2024-01-11 │ SKU_101 │ Chennai  │ 300.0         │ 70        ║
║ 2024-01-12 │ SKU_101 │ Chennai  │ 56.0          │ 65        ║
║ 2024-01-13 │ SKU_101 │ Chennai  │ 54.0          │ 60        ║
║ 2024-01-14 │ SKU_101 │ Chennai  │ 2.0           │ 55        ║
║ 2024-01-15 │ SKU_101 │ Chennai  │ 53.0          │ 50        ║
║ 2024-01-16 │ SKU_101 │ Chennai  │ 61.0          │ 45        ║
║ 2024-01-17 │ SKU_101 │ Chennai  │ 63.0          │ 40        ║
║ 2024-01-18 │ SKU_101 │ Chennai  │ 65.0          │ 35        ║
║ 2024-01-19 │ SKU_101 │ Chennai  │ nan           │ 30        ║
║ 2024-01-20 │ SKU_101 │ Chennai  │ 64.0          │ 25        ║
║ 2024-01-21 │ SKU_101 │ Chennai  │ 70.0          │ 20        ║
║ 2024-01-22 │ SKU_101 │ Chennai  │ 72.0          │ 15        ║
║ 2024-01-23 │ SKU_101 │ Chennai  │ 68.0          │ 10        ║
║ 2024-01-24 │ SKU_101 │ Chennai  │ 500.0         │ 5         ║
║ 2024-01-25 │ SKU_101 │ Chennai  │ 66.0          │ 0         ║
║ 2024-01-26 │ SKU_101 │ Chennai  │ 67.0          │ 0         ║
║ 2024-01-27 │ SKU_101 │ Chennai  │ 69.0          │ 0         ║
║ 2024-01-28 │ SKU_101 │ Chennai  │ 71.0          │ 10        ║
║ 2024-01-29 │ SKU_101 │ Chennai  │ 73.0          │ 15        ║
║ 2024-01-30 │ SKU_101 │ Chennai  │ 74.0          │ 20        ║
╚════════════╧═════════╧══════════╧═══════════════╧═══════════╝

========== Iteration 1 ==========

Guiding Agent → Display the entire dataset

Generated Code

import pandas as pd
import numpy as np

print(df)

╭─────────────────────────────────────────────── Execution Output ────────────────────────────────────────────────╮
│           date      sku location  quantity_sold  inventory                                                      │
│ 0   2024-01-01  SKU_101  Chennai           52.0        120                                                      │
│ 1   2024-01-02  SKU_101  Chennai           49.0        115                                                      │
│ 2   2024-01-03  SKU_101  Chennai            NaN        110                                                      │
│ 3   2024-01-04  SKU_101  Chennai           55.0        105                                                      │
│ 4   2024-01-05  SKU_101  Chennai           60.0        100                                                      │
│ 5   2024-01-06  SKU_101  Chennai           -5.0         95                                                      │
│ 6   2024-01-07  SKU_101  Chennai           58.0         90                                                      │
│ 7   2024-01-08  SKU_101  Chennai           62.0         85                                                      │
│ 8   2024-01-09  SKU_101  Chennai           59.0         80                                                      │
│ 9   2024-01-10  SKU_101  Chennai           57.0         75                                                      │
│ 10  2024-01-11  SKU_101  Chennai          300.0         70                                                      │
│ 11  2024-01-12  SKU_101  Chennai           56.0         65                                                      │
│ 12  2024-01-13  SKU_101  Chennai           54.0         60                                                      │
│ 13  2024-01-14  SKU_101  Chennai            2.0         55                                                      │
│ 14  2024-01-15  SKU_101  Chennai           53.0         50                                                      │
│ 15  2024-01-16  SKU_101  Chennai           61.0         45                                                      │
│ 16  2024-01-17  SKU_101  Chennai           63.0         40                                                      │
│ 17  2024-01-18  SKU_101  Chennai           65.0         35                                                      │
│ 18  2024-01-19  SKU_101  Chennai            NaN         30                                                      │
│ 19  2024-01-20  SKU_101  Chennai           64.0         25                                                      │
│ 20  2024-01-21  SKU_101  Chennai           70.0         20                                                      │
│ 21  2024-01-22  SKU_101  Chennai           72.0         15                                                      │
│ 22  2024-01-23  SKU_101  Chennai           68.0         10                                                      │
│ 23  2024-01-24  SKU_101  Chennai          500.0          5                                                      │
│ 24  2024-01-25  SKU_101  Chennai           66.0          0                                                      │
│ 25  2024-01-26  SKU_101  Chennai           67.0          0                                                      │
│ 26  2024-01-27  SKU_101  Chennai           69.0          0                                                      │
│ 27  2024-01-28  SKU_101  Chennai           71.0         10                                                      │
│ 28  2024-01-29  SKU_101  Chennai           73.0         15                                                      │
│ 29  2024-01-30  SKU_101  Chennai           74.0         20                                                      │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Checker Agent → Pending Preprocessing

========== Iteration 2 ==========

Guiding Agent → Print number of rows, number of columns and column names

Generated Code

import pandas as pd
import numpy as np

print("Number of rows: ", df.shape[0])
print("Number of columns: ", df.shape[1])
print("Column names: ", df.columns.tolist())

╭─────────────────────────────────────────────── Execution Output ────────────────────────────────────────────────╮
│ Number of rows:  30                                                                                             │
│ Number of columns:  5                                                                                           │
│ Column names:  ['date', 'sku', 'location', 'quantity_sold', 'inventory']                                        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Checker Agent → Pending Preprocessing

========== Iteration 3 ==========

Guiding Agent → Identify and print quantitative and qualitative columns

Generated Code

import pandas as pd
import numpy as np

numeric_columns = df.select_dtypes(include=np.number)
categorical_columns = df.select_dtypes(include="object")

print("Quantitative Columns:")
print(numeric_columns.columns)

print("\nQualitative Columns:")
print(categorical_columns.columns)

╭─────────────────────────────────────────────── Execution Output ────────────────────────────────────────────────╮
│ Quantitative Columns:                                                                                           │
│ Index(['quantity_sold', 'inventory'], dtype='object')                                                           │
│                                                                                                                 │
│ Qualitative Columns:                                                                                            │
│ Index(['date', 'sku', 'location'], dtype='object')                                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Checker Agent → Pending Preprocessing

========== Iteration 4 ==========

Guiding Agent → Detect missing values, print number of missing values and handle them

Generated Code

import pandas as pd
import numpy as np

# detect missing values
missing_values = df.isnull().sum()

# print number of missing values
print("Number of missing values:")
print(missing_values)

# handle missing values in numeric columns
numeric_cols = df.select_dtypes(include=np.number)
df[numeric_cols.columns] = numeric_cols.fillna(numeric_cols.mean())

# handle missing values in categorical columns
categorical_cols = df.select_dtypes(include="object")
df[categorical_cols.columns] = categorical_cols.fillna("Unknown")

# verify missing values
print("\nNumber of missing values after handling:")
print(df.isnull().sum())

╭─────────────────────────────────────────────── Execution Output ────────────────────────────────────────────────╮
│ Number of missing values:                                                                                       │
│ date             0                                                                                              │
│ sku              0                                                                                              │
│ location         0                                                                                              │
│ quantity_sold    2                                                                                              │
│ inventory        0                                                                                              │
│ dtype: int64                                                                                                    │
│                                                                                                                 │
│ Number of missing values after handling:                                                                        │
│ date             0                                                                                              │
│ sku              0                                                                                              │
│ location         0                                                                                              │
│ quantity_sold    0                                                                                              │
│ inventory        0                                                                                              │
│ dtype: int64                                                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Checker Agent → Pending Preprocessing

========== Iteration 5 ==========

Guiding Agent → Detect outliers, print high and low outliers and handle them using IQR

Generated Code

import pandas as pd
import numpy as np

numeric_cols = df.select_dtypes(include=np.number)

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    high_outliers = df[(df[col] > Q3 + 1.5 * IQR)]
    low_outliers = df[(df[col] < Q1 - 1.5 * IQR)]
    print(f"High outliers in {col}: {high_outliers.shape[0]}")
    print(f"Low outliers in {col}: {low_outliers.shape[0]}")

    df.loc[df[col] > Q3 + 1.5 * IQR, col] = Q3 + 1.5 * IQR
    df.loc[df[col] < Q1 - 1.5 * IQR, col] = Q1 - 1.5 * IQR

╭─────────────────────────────────────────────── Execution Output ────────────────────────────────────────────────╮
│ High outliers in quantity_sold: 2                                                                               │
│ Low outliers in quantity_sold: 2                                                                                │
│ High outliers in inventory: 0                                                                                   │
│ Low outliers in inventory: 0                                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Checker Agent → Pending Preprocessing

========== Iteration 6 ==========

Guiding Agent → Find duplicates and print number of duplicate rows

Generated Code

import pandas as pd
import numpy as np

duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

╭─────────────────────────────────────────────── Execution Output ────────────────────────────────────────────────╮
│ Number of duplicate rows: 0                                                                                     │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Checker Agent → Preprocessed Completely

Final Cleaned Dataset

                         Processed Dataset
╔════════════╤═════════╤══════════╤═══════════════════╤═══════════╗
║ date       │ sku     │ location │ quantity_sold     │ inventory ║
╟────────────┼─────────┼──────────┼───────────────────┼───────────╢
║ 2024-01-01 │ SKU_101 │ Chennai  │ 52.0              │ 120       ║
║ 2024-01-02 │ SKU_101 │ Chennai  │ 49.0              │ 115       ║
║ 2024-01-03 │ SKU_101 │ Chennai  │ 81.96428571428571 │ 110       ║
║ 2024-01-04 │ SKU_101 │ Chennai  │ 55.0              │ 105       ║
║ 2024-01-05 │ SKU_101 │ Chennai  │ 60.0              │ 100       ║
║ 2024-01-06 │ SKU_101 │ Chennai  │ 34.5              │ 95        ║
║ 2024-01-07 │ SKU_101 │ Chennai  │ 58.0              │ 90        ║
║ 2024-01-08 │ SKU_101 │ Chennai  │ 62.0              │ 85        ║
║ 2024-01-09 │ SKU_101 │ Chennai  │ 59.0              │ 80        ║
║ 2024-01-10 │ SKU_101 │ Chennai  │ 57.0              │ 75        ║
║ 2024-01-11 │ SKU_101 │ Chennai  │ 92.5              │ 70        ║
║ 2024-01-12 │ SKU_101 │ Chennai  │ 56.0              │ 65        ║
║ 2024-01-13 │ SKU_101 │ Chennai  │ 54.0              │ 60        ║
║ 2024-01-14 │ SKU_101 │ Chennai  │ 34.5              │ 55        ║
║ 2024-01-15 │ SKU_101 │ Chennai  │ 53.0              │ 50        ║
║ 2024-01-16 │ SKU_101 │ Chennai  │ 61.0              │ 45        ║
║ 2024-01-17 │ SKU_101 │ Chennai  │ 63.0              │ 40        ║
║ 2024-01-18 │ SKU_101 │ Chennai  │ 65.0              │ 35        ║
║ 2024-01-19 │ SKU_101 │ Chennai  │ 81.96428571428571 │ 30        ║
║ 2024-01-20 │ SKU_101 │ Chennai  │ 64.0              │ 25        ║
║ 2024-01-21 │ SKU_101 │ Chennai  │ 70.0              │ 20        ║
║ 2024-01-22 │ SKU_101 │ Chennai  │ 72.0              │ 15        ║
║ 2024-01-23 │ SKU_101 │ Chennai  │ 68.0              │ 10        ║
║ 2024-01-24 │ SKU_101 │ Chennai  │ 92.5              │ 5         ║
║ 2024-01-25 │ SKU_101 │ Chennai  │ 66.0              │ 0         ║
║ 2024-01-26 │ SKU_101 │ Chennai  │ 67.0              │ 0         ║
║ 2024-01-27 │ SKU_101 │ Chennai  │ 69.0              │ 0         ║
║ 2024-01-28 │ SKU_101 │ Chennai  │ 71.0              │ 10        ║
║ 2024-01-29 │ SKU_101 │ Chennai  │ 73.0              │ 15        ║
║ 2024-01-30 │ SKU_101 │ Chennai  │ 74.0              │ 20        ║
╚════════════╧═════════╧══════════╧═══════════════════╧═══════════╝

Dataset saved as Final_Dataset.csv

| **Step** | **Code Section**                              | **Agent**           | **Purpose**                                                                               | **Output**                                |
| -------- | --------------------------------------------- | ------------------- | ----------------------------------------------------------------------------------------- | ----------------------------------------- |
| 1        | Import Libraries                              | System              | Imports required Python libraries such as pandas, numpy, Groq, Rich, and IsolationForest. | Required packages loaded.                 |
| 2        | `GROQ_API_KEY = userdata.get("GROQ_API_KEY")` | System              | Retrieves the Groq API key securely from Google Colab Secrets.                            | API key available for the LLM.            |
| 3        | `console = Console()`                         | System              | Creates a Rich Console object for colorful terminal output.                               | Rich-formatted console.                   |
| 4        | `df = pd.read_csv("dataset.csv")`             | Data Loader         | Reads the CSV file into a pandas DataFrame.                                               | Dataset loaded into `df`.                 |
| 5        | Display Dataset Preview                       | Data Loader         | Displays the dataset as a formatted Rich table.                                           | Dataset preview shown.                    |
| 6        | `llm = ChatGroq(...)`                         | LLM Engine          | Initializes the Groq Large Language Model.                                                | AI model ready to generate code.          |
| 7        | `tasks = [...]`                               | **Guiding Agent**   | Defines the sequence of preprocessing tasks.                                              | Task list created.                        |
| 8        | `coder_agent(task)`                           | **Coding Agent**    | Sends each task to the Groq LLM and generates executable Python code.                     | Python preprocessing code generated.      |
| 9        | Display Generated Code                        | Coding Agent        | Shows the generated Python code with syntax highlighting.                                 | User can review generated code.           |
| 10       | `executor_agent(code)`                        | **Executor Agent**  | Executes the generated Python code using `exec()`.                                        | Dataset gets updated after each task.     |
| 11       | Capture Output                                | Executor Agent      | Captures `print()` statements from the executed code.                                     | Displays execution results.               |
| 12       | Update DataFrame                              | Executor Agent      | Saves the modified DataFrame back into the global `df`.                                   | Cleaned dataset retained.                 |
| 13       | Handle Errors                                 | Executor Agent      | Catches execution errors and displays them in a Rich panel.                               | Prevents program crashes.                 |
| 14       | `checker_agent(iteration)`                    | **Checker Agent**   | Verifies whether preprocessing is complete or still in progress.                          | Status message displayed.                 |
| 15       | `for i, task in enumerate(tasks)`             | Workflow Controller | Executes all preprocessing tasks one by one.                                              | Complete preprocessing pipeline executed. |
| 16       | Display Final Dataset                         | Result Viewer       | Displays the cleaned dataset in a Rich table.                                             | Final processed dataset shown.            |
| 17       | `df.to_csv(...)`                              | Save Agent          | Saves the cleaned dataset to a new CSV file.                                              | `Final_Dataset.csv` created.              |

Multi-Agent Architecture

| **Agent**          | **Function**                            | **Input**           | **Output**                             |
| ------------------ | --------------------------------------- | ------------------- | -------------------------------------- |
| **Guiding Agent**  | Decides the preprocessing task sequence | Task list           | Current preprocessing task             |
| **Coding Agent**   | Uses Groq LLM to generate Python code   | Task description    | Executable Python code                 |
| **Executor Agent** | Executes the generated code             | Python code         | Updated DataFrame and execution output |
| **Checker Agent**  | Monitors preprocessing progress         | Iteration count     | Pending or Completed status            |
| **Save Agent**     | Saves the final cleaned dataset         | Processed DataFrame | `Final_Dataset.csv`                    |

Overall Workflow

| **Stage**       | **Description**                                         |
| --------------- | ------------------------------------------------------- |
| Dataset Loading | Reads the input CSV file into a pandas DataFrame.       |
| Dataset Preview | Displays the dataset in a formatted table.              |
| Task Planning   | Guiding Agent selects the next preprocessing task.      |
| Code Generation | Coding Agent asks the Groq LLM to generate Python code. |
| Code Execution  | Executor Agent runs the generated code on the dataset.  |
| Progress Check  | Checker Agent verifies preprocessing progress.          |
| Final Output    | Displays and saves the cleaned dataset.                 |

Iteration 1
Guiding Agent
Display the entire dataset
What it does

The Guiding Agent decides the first preprocessing task.

Coding Agent

Generated Python code

print(df)

The Coding Agent asks the Groq LLM to write Python code for the assigned task.

Executor Agent

Output

Entire dataset displayed

The Executor Agent executes the generated code and prints all rows of the dataset. The original data includes missing values (NaN) and unusual values like -5, 300, and 500 in quantity_sold.

Checker Agent
Pending Preprocessing

This indicates preprocessing has started but is not yet complete.

Iteration 2
Guiding Agent
Print number of rows, number of columns and column names

The next task is to understand the dataset structure.

Coding Agent

Generates code like

print(df.shape)
print(df.columns)
Executor Agent

Output

Rows : 30
Columns : 5

Columns:
date
sku
location
quantity_sold
inventory

This tells us the dataset contains 30 records and 5 features.

Checker Agent
Pending Preprocessing
Iteration 3
Guiding Agent
Identify quantitative and qualitative columns

The goal is to classify the features.

Coding Agent

Generates code using

df.select_dtypes()
Executor Agent

Output

Quantitative Columns

quantity_sold
inventory

Qualitative Columns

date
sku
location

Meaning

Numeric Columns

quantity_sold
inventory

These can be used for mathematical operations.

Categorical Columns

date
sku
location

These contain labels or text.

Checker Agent
Pending Preprocessing
Iteration 4
Guiding Agent
Detect missing values and handle them

The objective is to clean incomplete data.

Coding Agent

Generates code using

df.isnull().sum()

fillna()
Executor Agent

Before cleaning

quantity_sold : 2 missing values

After cleaning

quantity_sold : 0 missing values

The missing values in the numeric column were replaced with the column mean, while categorical missing values would be filled with "Unknown" if present.

Checker Agent
Pending Preprocessing
Iteration 5
Guiding Agent
Detect outliers using IQR

The objective is to detect unusually high or low values.

Coding Agent

Generates code implementing the IQR method.

Executor Agent

Output

High outliers in quantity_sold : 2

Low outliers in quantity_sold : 2

The dataset originally contained values such as:

300
500
-5
2

These were detected as outliers and capped using the IQR limits. In the final dataset, 300 and 500 became 92.5, while -5 and 2 became 34.5.

Checker Agent
Pending Preprocessing
Iteration 6
Guiding Agent
Find duplicate rows

The objective is to detect repeated records.

Coding Agent

Generates

df.duplicated().sum()
Executor Agent

Output

Number of duplicate rows : 0

There are no duplicate rows in the dataset.

Checker Agent
Preprocessed Completely

This indicates that all planned preprocessing tasks have finished.

Final Output

The processed dataset is displayed and saved as Final_Dataset.csv. Compared with the original dataset:

Missing values were filled (for example, NaN in quantity_sold became 81.96428571428571).
Extreme high values (300, 500) were capped to 92.5.
Extreme low values (-5, 2) were raised to 34.5.
No duplicate rows needed removal.

| **Iteration**   | **Guiding Agent (Task)**                                               | **Coding Agent (Generated Code)**                                      | **Executor Agent (Execution Output)**                                                                                                                                                     | **Checker Agent**           |
| --------------- | ---------------------------------------------------------------------- | ---------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------- |
| **Iteration 1** | Display the entire dataset                                             | Generated `print(df)` to display the complete dataset.                 | Displayed all **30 rows** and **5 columns** of the dataset. Revealed missing values (`NaN`) and abnormal values such as `-5`, `300`, and `500` in `quantity_sold`.                        | **Pending Preprocessing**   |
| **Iteration 2** | Print number of rows, number of columns and column names               | Generated code using `df.shape` and `df.columns`.                      | Printed **30 rows**, **5 columns**, and column names: `date`, `sku`, `location`, `quantity_sold`, `inventory`.                                                                            | **Pending Preprocessing**   |
| **Iteration 3** | Identify quantitative and qualitative columns                          | Generated code using `df.select_dtypes()`.                             | Identified **Quantitative Columns:** `quantity_sold`, `inventory`.<br>**Qualitative Columns:** `date`, `sku`, `location`.                                                                 | **Pending Preprocessing**   |
| **Iteration 4** | Detect missing values, print number of missing values and handle them  | Generated code using `df.isnull().sum()` and `fillna()`.               | Found **2 missing values** in `quantity_sold`. Replaced missing numeric values with the column mean and verified that **no missing values remained**.                                     | **Pending Preprocessing**   |
| **Iteration 5** | Detect outliers, print high and low outliers and handle them using IQR | Generated code implementing the **IQR (Interquartile Range)** method.  | Detected **2 high outliers** (`300`, `500`) and **2 low outliers** (`-5`, `2`) in `quantity_sold`. Capped them to the IQR upper and lower limits. No outliers were found in `inventory`.  | **Pending Preprocessing**   |
| **Iteration 6** | Find duplicates and print number of duplicate rows                     | Generated code using `df.duplicated().sum()`.                          | Checked for duplicate records and found **0 duplicate rows**. No records were removed.                                                                                                    | **Preprocessed Completely** |

Complete Agent Communication Flow

                      dataset.csv
                          │
                          ▼
                Data Loader Agent
                          │
            Loads dataset into DataFrame
                          │
                          ▼
                Guiding Agent
            "What should we do next?"
                          │
                          ▼
                Coding Agent (Groq)
            Generates Python code
                          │
                          ▼
                Executor Agent
            Runs generated Python code
                          │
                          ▼
                Checker Agent
            Verifies task completion
                          │
              More tasks remaining?
                  │            │
                Yes          No
                  │            │
                  ▼            ▼
            Next Iteration   Save Final_Dataset.csv

In [8]:
df

          date      sku location  quantity_sold  inventory
0   2024-01-01  SKU_101  Chennai      52.000000        120
1   2024-01-02  SKU_101  Chennai      49.000000        115
2   2024-01-03  SKU_101  Chennai      81.964286        110
3   2024-01-04  SKU_101  Chennai      55.000000        105
4   2024-01-05  SKU_101  Chennai      60.000000        100
5   2024-01-06  SKU_101  Chennai      34.500000         95
6   2024-01-07  SKU_101  Chennai      58.000000         90
7   2024-01-08  SKU_101  Chennai      62.000000         85
8   2024-01-09  SKU_101  Chennai      59.000000         80
9   2024-01-10  SKU_101  Chennai      57.000000         75
10  2024-01-11  SKU_101  Chennai      92.500000         70
11  2024-01-12  SKU_101  Chennai      56.000000         65
12  2024-01-13  SKU_101  Chennai      54.000000         60
13  2024-01-14  SKU_101  Chennai      34.500000         55
14  2024-01-15  SKU_101  Chennai      53.000000         50
15  2024-01-16  SKU_101  Chennai      61.000000         45
16  2024-01-17  SKU_101  Chennai      63.000000         40
17  2024-01-18  SKU_101  Chennai      65.000000         35
18  2024-01-19  SKU_101  Chennai      81.964286         30
19  2024-01-20  SKU_101  Chennai      64.000000         25
20  2024-01-21  SKU_101  Chennai      70.000000         20
21  2024-01-22  SKU_101  Chennai      72.000000         15
22  2024-01-23  SKU_101  Chennai      68.000000         10
23  2024-01-24  SKU_101  Chennai      92.500000          5
24  2024-01-25  SKU_101  Chennai      66.000000          0
25  2024-01-26  SKU_101  Chennai      67.000000          0
26  2024-01-27  SKU_101  Chennai      69.000000          0
27  2024-01-28  SKU_101  Chennai      71.000000         10
28  2024-01-29  SKU_101  Chennai      73.000000         15
29  2024-01-30  SKU_101  Chennai      74.000000         20

In [10]:
import pandas as pd

# Original dataset
data = pd.read_csv("/content/dataset.csv")
display(data)

# Final dataset
final_data = pd.read_csv("/content/Final_Dataset.csv")
display(final_data)

          date      sku location  quantity_sold  inventory
0   2024-01-01  SKU_101  Chennai           52.0        120
1   2024-01-02  SKU_101  Chennai           49.0        115
2   2024-01-03  SKU_101  Chennai            NaN        110
3   2024-01-04  SKU_101  Chennai           55.0        105
4   2024-01-05  SKU_101  Chennai           60.0        100
5   2024-01-06  SKU_101  Chennai           -5.0         95
6   2024-01-07  SKU_101  Chennai           58.0         90
7   2024-01-08  SKU_101  Chennai           62.0         85
8   2024-01-09  SKU_101  Chennai           59.0         80
9   2024-01-10  SKU_101  Chennai           57.0         75
10  2024-01-11  SKU_101  Chennai          300.0         70
11  2024-01-12  SKU_101  Chennai           56.0         65
12  2024-01-13  SKU_101  Chennai           54.0         60
13  2024-01-14  SKU_101  Chennai            2.0         55
14  2024-01-15  SKU_101  Chennai           53.0         50
15  2024-01-16  SKU_101  Chennai           61.0         45
16  2024-01-17  SKU_101  Chennai           63.0         40
17  2024-01-18  SKU_101  Chennai           65.0         35
18  2024-01-19  SKU_101  Chennai            NaN         30
19  2024-01-20  SKU_101  Chennai           64.0         25
20  2024-01-21  SKU_101  Chennai           70.0         20
21  2024-01-22  SKU_101  Chennai           72.0         15
22  2024-01-23  SKU_101  Chennai           68.0         10
23  2024-01-24  SKU_101  Chennai          500.0          5
24  2024-01-25  SKU_101  Chennai           66.0          0
25  2024-01-26  SKU_101  Chennai           67.0          0
26  2024-01-27  SKU_101  Chennai           69.0          0
27  2024-01-28  SKU_101  Chennai           71.0         10
28  2024-01-29  SKU_101  Chennai           73.0         15
29  2024-01-30  SKU_101  Chennai           74.0         20

          date      sku location  quantity_sold  inventory
0   2024-01-01  SKU_101  Chennai      52.000000        120
1   2024-01-02  SKU_101  Chennai      49.000000        115
2   2024-01-03  SKU_101  Chennai      81.964286        110
3   2024-01-04  SKU_101  Chennai      55.000000        105
4   2024-01-05  SKU_101  Chennai      60.000000        100
5   2024-01-06  SKU_101  Chennai      34.500000         95
6   2024-01-07  SKU_101  Chennai      58.000000         90
7   2024-01-08  SKU_101  Chennai      62.000000         85
8   2024-01-09  SKU_101  Chennai      59.000000         80
9   2024-01-10  SKU_101  Chennai      57.000000         75
10  2024-01-11  SKU_101  Chennai      92.500000         70
11  2024-01-12  SKU_101  Chennai      56.000000         65
12  2024-01-13  SKU_101  Chennai      54.000000         60
13  2024-01-14  SKU_101  Chennai      34.500000         55
14  2024-01-15  SKU_101  Chennai      53.000000         50
15  2024-01-16  SKU_101  Chennai      61.000000         45
16  2024-01-17  SKU_101  Chennai      63.000000         40
17  2024-01-18  SKU_101  Chennai      65.000000         35
18  2024-01-19  SKU_101  Chennai      81.964286         30
19  2024-01-20  SKU_101  Chennai      64.000000         25
20  2024-01-21  SKU_101  Chennai      70.000000         20
21  2024-01-22  SKU_101  Chennai      72.000000         15
22  2024-01-23  SKU_101  Chennai      68.000000         10
23  2024-01-24  SKU_101  Chennai      92.500000          5
24  2024-01-25  SKU_101  Chennai      66.000000          0
25  2024-01-26  SKU_101  Chennai      67.000000          0
26  2024-01-27  SKU_101  Chennai      69.000000          0
27  2024-01-28  SKU_101  Chennai      71.000000         10
28  2024-01-29  SKU_101  Chennai      73.000000         15
29  2024-01-30  SKU_101  Chennai      74.000000         20

In [11]:
print("Original Dataset")
display(data.head(10))

print("Final Dataset")
display(final_data.head(10))

Original Dataset

         date      sku location  quantity_sold  inventory
0  2024-01-01  SKU_101  Chennai           52.0        120
1  2024-01-02  SKU_101  Chennai           49.0        115
2  2024-01-03  SKU_101  Chennai            NaN        110
3  2024-01-04  SKU_101  Chennai           55.0        105
4  2024-01-05  SKU_101  Chennai           60.0        100
5  2024-01-06  SKU_101  Chennai           -5.0         95
6  2024-01-07  SKU_101  Chennai           58.0         90
7  2024-01-08  SKU_101  Chennai           62.0         85
8  2024-01-09  SKU_101  Chennai           59.0         80
9  2024-01-10  SKU_101  Chennai           57.0         75

Final Dataset

         date      sku location  quantity_sold  inventory
0  2024-01-01  SKU_101  Chennai      52.000000        120
1  2024-01-02  SKU_101  Chennai      49.000000        115
2  2024-01-03  SKU_101  Chennai      81.964286        110
3  2024-01-04  SKU_101  Chennai      55.000000        105
4  2024-01-05  SKU_101  Chennai      60.000000        100
5  2024-01-06  SKU_101  Chennai      34.500000         95
6  2024-01-07  SKU_101  Chennai      58.000000         90
7  2024-01-08  SKU_101  Chennai      62.000000         85
8  2024-01-09  SKU_101  Chennai      59.000000         80
9  2024-01-10  SKU_101  Chennai      57.000000         75

The preprocessing agents have modified only the problematic values, while leaving the correct values unchanged.

|   Row | Original Dataset | Final Dataset | What happened?                                      |
| ----: | ---------------- | ------------- | --------------------------------------------------- |
|     0 | 52.0             | 52.0          | No change                                           |
|     1 | 49.0             | 49.0          | No change                                           |
| **2** | **NaN**          | **81.964286** | ✅ Missing value filled (Imputation Agent)           |
|     3 | 55.0             | 55.0          | No change                                           |
|     4 | 60.0             | 60.0          | No change                                           |
| **5** | **-5.0**         | **34.5**      | ✅ Negative value corrected (Outlier/Cleaning Agent) |
|     6 | 58.0             | 58.0          | No change                                           |
|     7 | 62.0             | 62.0          | No change                                           |
|     8 | 59.0             | 59.0          | No change                                           |
|     9 | 57.0             | 57.0          | No change                                           |


====

| Agent                    | Input                     | Output               |
| ------------------------ | ------------------------- | -------------------- |
| Missing Value Agent      | `NaN`                     | `81.964286`          |
| Outlier Validation Agent | `-5.0`                    | Flagged as invalid   |
| Data Cleaning Agent      | `-5.0`                    | Replaced with `34.5` |
| Validation Agent         | Checked final dataset     | Passed               |
| Save Agent               | Saved `Final_Dataset.csv` | Completed            |

✅ Missing value imputation
✅ Negative value correction
✅ Extreme outlier handling
✅ Invalid text-to-number cleaning
✅ Inventory validation
✅ Duplicate removal (if added)
✅ Data type conversion
✅ Final validation